language: node_js
node_js:
  - "8"
dist: xenial  
sudo: required
services:
  - docker

env:
  global:
    - DOCKER_TLS_VERIFY="1"
    - DOCKER_HOST="tcp://52.160.82.166:2376"
    - DOCKER_CERT_PATH="$TRAVIS_BUILD_DIR/azure"
    - DOCKER_MACHINE_NAME="dronuts-2019-group-3"

script:
  - npm test
  - travis_wait 500 docker-compose build

deploy:
  skip_cleanup: true
  provider: script
  script: docker-compose up -d --remove-orphans
  on:
    branch: master
